# 强制使用 XeLaTeX 模式
$pdf_mode = 5; 
$postscript_mode = $dvi_mode = 0;

# 显式定义所有 pdf 编译动作都指向 xelatex
$pdflatex = 'xelatex -synctex=1 -interaction=nonstopmode -file-line-error %O %S';
$xelatex  = 'xelatex -synctex=1 -interaction=nonstopmode -file-line-error %O %S';

# 参考文献设置
$bibtex_use = 2;